//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LavaJatodoMartins
{
    using System;
    using System.Collections.Generic;
    
    public partial class agendamentos
    {
        public int id { get; set; }
        public System.DateTime data { get; set; }
        public string veiculo { get; set; }
        public int servico { get; set; }
        public decimal valor { get; set; }
    
        public virtual servicos servicos { get; set; }
        public virtual veiculos veiculos { get; set; }
    }
}
